version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
  settings:
    gosec:
      excludes:
        - G304
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
    - goimports
